name: Test
on:
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: getong/mariadb-action@v1.11
        with:
          character set server: 'utf8mb4'
          collation server: 'utf8mb4_czech_ci'
          mariadb version: '10.4.10'
          mysql database: 'acs'
          mysql root password: test
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Test
        run: ./gradlew test
        env:
          DATABASE_URL: mariadb://localhost:3306/acs?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
          DATABASE_USER: root
          DATABASE_PASSWORD: test